### PR TITLE
fix AttributeError when reading metadata dict

### LINKED ISSUE #31: colcon build failing on python modules
Version used: 0.24
OS: Ubuntu Bionic x86_64
ROS version: melodic

Steps to reproduce break:
1. install latest colcon from pip
1. create a new workspace
1. clone https://github.com/zmichaels11/test-py-module into workspace
1. run `colcon build`

This works on version 0.23, which can be acquired from apt.

### PR DESCRIPTION
**Pull request by dirk-thomas**
Resolve regression introduced in #30. Fixes #31.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
> This will change the exception to a log.

Can you please clarify what kind of "log" you are referring to?

Before the build fails with an `AttributeError` for me (see referenced issue). With the patch the package builds as expected and I don't see any messages indicating problems.

> Does this allow a python module to still build?

I don't know what you mean with this. Before the package build was not even attempted since the metadata couldn't be processed correctly. After the build is invoked and passes.

**Comment by zmichaels11** [comment]
Confirmed this does build the package.
```bash
ubuntu@hostname:~/ws$ colcon build --event-handlers console_direct+
Starting >>> test-py-module
running egg_info                             
writing /home/ubuntu/ws/build/test-py-module/test_py_module.egg-info/PKG-INFO
writing dependency_links to /home/ubuntu/ws/build/test-py-module/test_py_module.egg-info/dependency_links.txt
writing requirements to /home/ubuntu/ws/build/test-py-module/test_py_module.egg-info/requires.txt
writing top-level names to /home/ubuntu/ws/build/test-py-module/test_py_module.egg-info/top_level.txt
reading manifest file '/home/ubuntu/ws/build/test-py-module/test_py_module.egg-info/SOURCES.txt'
writing manifest file '/home/ubuntu/ws/build/test-py-module/test_py_module.egg-info/SOURCES.txt'
running build
running build_py
running install
running install_lib
running install_egg_info
removing '/home/ubuntu/ws/install/test-py-module/lib/python3.6/site-packages/test_py_module-0.1-py3.6.egg-info' (and everything under it)
Copying /home/ubuntu/ws/build/test-py-module/test_py_module.egg-info to /home/ubuntu/ws/install/test-py-module/lib/python3.6/site-packages/test_py_module-0.1-py3.6.egg-info
running install_scripts
writing list of installed files to '/home/ubuntu/ws/build/test-py-module/install.log'
Finished <<< test-py-module [0.71s]          

Summary: 1 package finished [1.32s]
```

<updating with console_direct+ output from version 0.23 for comparison>

**Comment by zmichaels11** [comment]
@dirk-thomas I updated the previous comment with the output from version 0.23 (installed via apt) and it looks like it did more in the previous version.

**Comment by dirk-thomas** [comment]
I do the the same output as before - the one you mentioned as expected output with this patch. Are you sure you performed both builds from a clean - not previously built - workspace?

**Pull request merged**
